# docker-compose-dev.yml
networks:
  net-pub:
    external: true

services:
  redis:
    image: redis
    container_name: spring-redis
    ports:
      - 6379:6379
    networks:
      - net-pub

  spring:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - redis
    networks:
      - net-pub
    entrypoint:
      - "java"
      - "-Dspring.profiles.active=dev"
      - "-jar"
      - "/app.jar"
