# docker-compose-release.yml
networks:
  net-release:
    external: true

services:
  redis:
    image: redis
    container_name: spring-redis
    ports:
      - 6385:6379
    networks:
      - net-release

  backend:
    build: .
    ports:
      - 8088:8080
    depends_on:
      - redis
    networks:
      - net-release
    entrypoint:
      - "java"
      - "-Dspring.profiles.active=release"
      - "-jar"
      - "/app.jar"