# docker-compose.yml
services:
  spring:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - redis
    networks:
      - net-pub

  redis:
    image: redis
    container_name: spring-redis
    ports:
      - 6379:6379
    networks:
      - net-pub

networks:
  net-pub:
    external: true
