spring:
  datasource:
    url: jdbc:mysql://spring-mysql:3306/zigzagdb 
    username: user
    password: pwd
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: create

  # h2: #H2 Configuration
  #   console:
  #     enabled: true
  #     path: /h2-console

  # datasource:
  #   driver-class-name: org.h2.Driver
  #   url: jdbc:h2:~/test;
  #   username: sa
  #   password:

  # jpa: #JPA Configuration
  #   database-platform: org.hibernate.dialect.H2Dialect
  #   hibernate:
  #     ddl-auto: create
    # properties:
    #   hibernate:
    #     format_sql: true
    #     show_sql: true

  profiles:
    default:
      - local 

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

server:
  port: 8080
  servlet:
    context-path: /api

# Jwt Configuration => 분리 필요
jwt:
  secret-key: asd19i23hj909sfua9s0fdusd90fua9023fjnh
  access:
    expiration: 3600000
    header: Authorization
  refresh:
    expiration: 1209600000
    header: Set-Cookie