spring:
  config:
    activate:
      on-profile: dev

  #OAuth2 Configuration
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 574121728411-si5ub2jih5ua9h8jtt0jatf72qsrt00p.apps.googleusercontent.com
            client-secret: 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
            scope:
              - profile
              - email
            redirect-uri: http://k9a407.p.ssafy.io:8080/api/login/oauth2/code/google

  # Redis Configuration
  data:
    redis:
      host: redis
      password:
      port: 6379