# 로컬 프론트 & 배포 백엔드
spring:
  config:
    activate:
      on-profile: dev

  # DB & JPA Configuration
  datasource:
    url: jdbc:mysql://mysql-dev:3306/zigzagdb
    username: root
    password: rootpwd
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        dialect : org.hibernate.dialect.MySQLDialect
        show-sql: true
    hibernate:
      ddl-auto: none

  #OAuth2 Configuration
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 574121728411-si5ub2jih5ua9h8jtt0jatf72qsrt00p.apps.googleusercontent.com
            client-secret: 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
            scope:
              - profile
              - email
            redirect-uri: ${base-url.backend}/api/login/oauth2/code/google

  # Redis Configuration
  data:
    redis:
      host: redis-dev
      password:
      port: 6379

server:
  port: 8080
  servlet:
    context-path: /dev/api

base-url:
  frontend: http://localhost:3000
  backend: http://ziglog.site:8080