#OAuth2 Configuration
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 574121728411-si5ub2jih5ua9h8jtt0jatf72qsrt00p.apps.googleusercontent.com
            client-secret: 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
            scope:
              - profile
              - email
            redirect-uri: http://k9a407.p.ssafy.io:8080/api/login/oauth2/code/google

#JWTtoken configurations
jwt:
  secret-key: asd19i23hj909sfua9s0fdusd90fua9023fjnh
  access:
    expiration: 3600000
    header: Authorization
  refresh:
    expiration: 1209600000
    header: Set-Cookie
