spring:
  config:
    activate:
      on-profile: local
  data:
    redis:
      host: 127.0.0.1
      password:
      port: 6379
---
spring:
  config:
    activate:
      on-profile: dev
  data:
    redis:
      host: redis
      password:
      port: 6379
