spring:
  profiles:
    default:
      - local 

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

# Jwt Configuration => 분리 필요
jwt:
  secret-key: asd19i23hj909sfua9s0fdusd90fua9023fjnh
  access:
    expiration: 3600000
    header: Authorization
  refresh:
    expiration: 1209600000
    header: Set-Cookie
