


spring:
  config:
    activate:
      on-profile: local

  h2: #H2 Configuration
    console:
      enabled: true
      path: /h2-console

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/test;
    username: sa
    password:

  jpa: #JPA Configuration
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  #OAuth2 Configuration
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 574121728411-si5ub2jih5ua9h8jtt0jatf72qsrt00p.apps.googleusercontent.com
            client-secret: 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
            scope:
              - profile
              - email
            redirect-uri: ${base-url.backend}/api/login/oauth2/code/google

  # Redis Configuration
  data:
    redis:
      host: 127.0.0.1
      password:
      port: 6379

base-url:
  frontend: http://localhost:3000
  backend: http://localhost:8080